# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finder.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Finder(object):
    def setupUi(self, Finder):
        Finder.setObjectName("Finder")
        Finder.resize(688, 683)
        self.verticalLayout = QtWidgets.QVBoxLayout(Finder)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_path = QtWidgets.QLineEdit(Finder)
        self.lineEdit_path.setText("")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout.addWidget(self.lineEdit_path)
        self.file_review = QtWidgets.QPushButton(Finder)
        self.file_review.setObjectName("file_review")
        self.horizontalLayout.addWidget(self.file_review)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_pattern = QtWidgets.QLineEdit(Finder)
        self.lineEdit_pattern.setText("")
        self.lineEdit_pattern.setObjectName("lineEdit_pattern")
        self.horizontalLayout_2.addWidget(self.lineEdit_pattern)
        self.comboBox_filter = QtWidgets.QComboBox(Finder)
        self.comboBox_filter.setObjectName("comboBox_filter")
        self.comboBox_filter.addItem("")
        self.comboBox_filter.addItem("")
        self.comboBox_filter.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_filter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.checkBox_file_size = QtWidgets.QCheckBox(Finder)
        self.checkBox_file_size.setObjectName("checkBox_file_size")
        self.verticalLayout.addWidget(self.checkBox_file_size)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(Finder)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_file_size_filter = QtWidgets.QLineEdit(Finder)
        self.lineEdit_file_size_filter.setStyleSheet("background-color: gray;")
        self.lineEdit_file_size_filter.setReadOnly(True)
        self.lineEdit_file_size_filter.setObjectName("lineEdit_file_size_filter")
        self.horizontalLayout_3.addWidget(self.lineEdit_file_size_filter)
        self.label_2 = QtWidgets.QLabel(Finder)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.find = QtWidgets.QPushButton(Finder)
        self.find.setObjectName("find")
        self.verticalLayout.addWidget(self.find)
        self.listWidget_pathes = QtWidgets.QListWidget(Finder)
        self.listWidget_pathes.setObjectName("listWidget_pathes")
        self.verticalLayout.addWidget(self.listWidget_pathes)
        self.open_path_file = QtWidgets.QPushButton(Finder)
        self.open_path_file.setObjectName("open_path_file")
        self.verticalLayout.addWidget(self.open_path_file)

        self.retranslateUi(Finder)
        QtCore.QMetaObject.connectSlotsByName(Finder)

    def retranslateUi(self, Finder):
        _translate = QtCore.QCoreApplication.translate
        Finder.setWindowTitle(_translate("Finder", "Form"))
        self.lineEdit_path.setPlaceholderText(_translate("Finder", "Путь к папке"))
        self.file_review.setText(_translate("Finder", "Обзор"))
        self.lineEdit_pattern.setPlaceholderText(_translate("Finder", "Паттерн"))
        self.comboBox_filter.setItemText(0, _translate("Finder", "Строки"))
        self.comboBox_filter.setItemText(1, _translate("Finder", "Бинарный"))
        self.comboBox_filter.setItemText(2, _translate("Finder", "Байты"))
        self.checkBox_file_size.setText(_translate("Finder", "Размер файлов"))
        self.label.setText(_translate("Finder", "Искать в файлах размером меньше"))
        self.label_2.setText(_translate("Finder", "байт"))
        self.find.setText(_translate("Finder", "Искать"))
        self.open_path_file.setText(_translate("Finder", "Открыть папук с файлом"))
